# Generated by Django 4.1 on 2022-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_bulletinboard_updated_at_alter_bulletinboard_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinboard',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
