# Generated by Django 4.1 on 2022-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_bulletinboard_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='weather',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
